export const LOAD_LEAGUES_SUCCESS = "LOAD_LEAGUES_SUCCESS";
export const LOAD_REGIONS_SUCCESS = "LOAD_REGIONS_SUCCESS";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const LOAD_SEASONS_SUCCESS = "LOAD_SEASONS_SUCCESS";
