// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoringDepthReact.Models;

namespace ScoringDepthReact.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190724012002_feedback")]
    partial class feedback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.Country", b =>
                {
                    b.Property<long>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.Feedback", b =>
                {
                    b.Property<long>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ContactMe");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsProcessed");

                    b.Property<string>("LastName");

                    b.Property<string>("Message");

                    b.Property<string>("Role");

                    b.HasKey("FeedbackId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.League", b =>
                {
                    b.Property<long>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("LeagueId");

                    b.ToTable("League");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.Region", b =>
                {
                    b.Property<long>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("RegionId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.Season", b =>
                {
                    b.Property<long>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("YearStart");

                    b.HasKey("SeasonId");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.SeasonLeague", b =>
                {
                    b.Property<long>("SeasonId");

                    b.Property<long>("CountryId");

                    b.Property<long>("LeagueId");

                    b.Property<long>("RegionId");

                    b.Property<long>("TeamId");

                    b.Property<long>("WeekRankingId");

                    b.HasKey("SeasonId", "CountryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("RegionId");

                    b.HasIndex("TeamId");

                    b.HasIndex("WeekRankingId");

                    b.ToTable("SeasonLeague");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.Team", b =>
                {
                    b.Property<long>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("TeamId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.WeekRanking", b =>
                {
                    b.Property<long>("WeekRankingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Sdi");

                    b.Property<int>("Week");

                    b.HasKey("WeekRankingId");

                    b.ToTable("WeekRanking");
                });

            modelBuilder.Entity("ScoringDepthReact.Models.Domain.SeasonLeague", b =>
                {
                    b.HasOne("ScoringDepthReact.Models.Domain.Country", "Country")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScoringDepthReact.Models.Domain.League", "League")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScoringDepthReact.Models.Domain.Region", "Region")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScoringDepthReact.Models.Domain.Season", "Season")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScoringDepthReact.Models.Domain.Team", "Team")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScoringDepthReact.Models.Domain.WeekRanking", "WeekRanking")
                        .WithMany("SeasonLeague")
                        .HasForeignKey("WeekRankingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
